spring.application.name=Ordenes_Transporte
#dddd

# Configuración de la base de datos postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/ordTransport
spring.datasource.username=postgres
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuración de JPA (opcional)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=/api/v1
server.port=9091